### ISSUE TITLE
Build error in Humble

### ISSUE THREAD

**Issue by YazanRihan** [arshadlab/gazebo_map_creator#2]
I am following the same instructions, my distro is humble and working on Ubuntu 22.04
Here's the colcon build output:
```
--- stderr: gazebo_map_creator                               
** WARNING ** io features related to pcap will be disabled
In file included from /usr/include/boost/gil/extension/io/png/detail/read.hpp:16,
                 from /usr/include/boost/gil/extension/io/png/read.hpp:14,
                 from /usr/include/boost/gil/extension/io/png.hpp:11,
                 from /usr/include/boost/gil/extension/io/png/old.hpp:11,
                 from /home/rihanadm/robot_ws/src/gazebo_map_creator/gazebo_map_creator/src/gazbeo_map_creator.cpp:28:
/usr/include/boost/gil/io/detail/dynamic.hpp:21:8: error: redefinition of ‘struct boost::gil::detail::construct_matched_t<N>’
   21 | struct construct_matched_t
      |        ^~~~~~~~~~~~~~~~~~~
In file included from /home/rihanadm/robot_ws/src/gazebo_map_creator/gazebo_map_creator/src/gazbeo_map_creator.cpp:27:
/usr/include/boost/gil/io/dynamic_io_new.hpp:23:8: note: previous definition of ‘struct boost::gil::detail::construct_matched_t<N>’
   23 | struct construct_matched_t
      |        ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/gil/extension/io/png/detail/read.hpp:16,
                 from /usr/include/boost/gil/extension/io/png/read.hpp:14,
                 from /usr/include/boost/gil/extension/io/png.hpp:11,
                 from /usr/include/boost/gil/extension/io/png/old.hpp:11,
                 from /home/rihanadm/robot_ws/src/gazebo_map_creator/gazebo_map_creator/src/gazbeo_map_creator.cpp:28:
/usr/include/boost/gil/io/detail/dynamic.hpp:38:8: error: redefinition of ‘struct boost::gil::detail::construct_matched_t<0>’
   38 | struct construct_matched_t<0>
      |        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/rihanadm/robot_ws/src/gazebo_map_creator/gazebo_map_creator/src/gazbeo_map_creator.cpp:27:
/usr/include/boost/gil/io/dynamic_io_new.hpp:40:8: note: previous definition of ‘struct boost::gil::detail::construct_matched_t<0>’
   40 | struct construct_matched_t<0>
      |        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/gil/extension/io/png/detail/read.hpp:16,
                 from /usr/include/boost/gil/extension/io/png/read.hpp:14,
                 from /usr/include/boost/gil/extension/io/png.hpp:11,
                 from /usr/include/boost/gil/extension/io/png/old.hpp:11,
                 from /home/rihanadm/robot_ws/src/gazebo_map_creator/gazebo_map_creator/src/gazbeo_map_creator.cpp:28:
/usr/include/boost/gil/io/detail/dynamic.hpp:48:7: error: redefinition of ‘class boost::gil::detail::dynamic_io_fnobj<IsSupported, OpClass>’
   48 | class dynamic_io_fnobj
      |       ^~~~~~~~~~~~~~~~
In file included from /home/rihanadm/robot_ws/src/gazebo_map_creator/gazebo_map_creator/src/gazbeo_map_creator.cpp:27:
/usr/include/boost/gil/io/dynamic_io_new.hpp:50:7: note: previous definition of ‘class boost::gil::detail::dynamic_io_fnobj<IsSupported, OpClass>’
   50 | class dynamic_io_fnobj
      |       ^~~~~~~~~~~~~~~~
In file included from /usr/include/boost/algorithm/string/finder.hpp:23,
                 from /usr/include/boost/algorithm/string/find.hpp:22,
                 from /usr/include/boost/algorithm/string/predicate.hpp:24,
                 from /usr/include/pcl-1.12/pcl/io/file_io.h:47,
                 from /usr/include/pcl-1.12/pcl/io/pcd_io.h:45,
                 from /home/rihanadm/robot_ws/src/gazebo_map_creator/gazebo_map_creator/src/gazbeo_map_creator.cpp:30:
/usr/include/boost/algorithm/string/detail/finder.hpp: In member function ‘boost::iterator_range<Iterator> boost::algorithm::detail::first_finderF<SearchIteratorT, PredicateT>::operator()(ForwardIteratorT, ForwardIteratorT) const’:
/usr/include/boost/algorithm/string/detail/finder.hpp:67: note: ‘-Wmisleading-indentation’ is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
   67 |                         if( boost::empty(m_Search) )
      | 
/usr/include/boost/algorithm/string/detail/finder.hpp:67: note: adding ‘-flarge-source-files’ will allow for more column-tracking support, at the expense of compilation time and memory
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-inconsistent-missing-override’ may have been intended to silence earlier diagnostics
gmake[2]: *** [CMakeFiles/gazebo_map_creator.dir/build.make:76: CMakeFiles/gazebo_map_creator.dir/src/gazbeo_map_creator.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/gazebo_map_creator.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< gazebo_map_creator [14.8s, exited with code 2]

```

**Comment by arshadlab** [comment]
I have been using humble+ubuntu 22.04 without encountering any problems. It's possible that the issue you mentioned is specific to your setup. As an additional verification, I downloaded a fresh Docker image and successfully compiled it without encountering any errors.

docker pull osrf/ros:humble-desktop-jammy
docker run ....  osrf/ros:humble-desktop-jammy
In docker container ->
cd <path>/robot_ws/
sudo apt-get update
rosdep install --from-paths ./src --ignore-src  -r -y
colcon build

**Comment by YazanRihan** [comment]
@arshadlab 

Could you let me know of the version of Boost libraries you tried it on?

**Comment by arshadlab** [comment]
libboost1.74-dev:amd64

**Comment by Charifou** [comment]
I have the same compilation error. Have you found a solution ?
libboost version 1.74.0.3ubuntu7.
